//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOR_Extended_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOnOff {
            get {
                return ((string)(this["settingOnOff"]));
            }
            set {
                this["settingOnOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingNickname {
            get {
                return ((string)(this["settingNickname"]));
            }
            set {
                this["settingNickname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHealth {
            get {
                return ((string)(this["settingHealth"]));
            }
            set {
                this["settingHealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingMounted {
            get {
                return ((string)(this["settingMounted"]));
            }
            set {
                this["settingMounted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingItems {
            get {
                return ((string)(this["settingItems"]));
            }
            set {
                this["settingItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingItemsDev {
            get {
                return ((string)(this["settingItemsDev"]));
            }
            set {
                this["settingItemsDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpells {
            get {
                return ((string)(this["settingSpells"]));
            }
            set {
                this["settingSpells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpellsDev {
            get {
                return ((string)(this["settingSpellsDev"]));
            }
            set {
                this["settingSpellsDev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDistance {
            get {
                return ((string)(this["settingDistance"]));
            }
            set {
                this["settingDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingGuild {
            get {
                return ((string)(this["settingGuild"]));
            }
            set {
                this["settingGuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSound {
            get {
                return ((string)(this["settingSound"]));
            }
            set {
                this["settingSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDrawFilteredPlayers {
            get {
                return ((string)(this["settingDrawFilteredPlayers"]));
            }
            set {
                this["settingDrawFilteredPlayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDrawFilteredGuilds {
            get {
                return ((string)(this["settingDrawFilteredGuilds"]));
            }
            set {
                this["settingDrawFilteredGuilds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDrawFilteredAlliances {
            get {
                return ((string)(this["settingDrawFilteredAlliances"]));
            }
            set {
                this["settingDrawFilteredAlliances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mainWindowMarginX {
            get {
                return ((string)(this["mainWindowMarginX"]));
            }
            set {
                this["mainWindowMarginX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mainWindowMarginY {
            get {
                return ((string)(this["mainWindowMarginY"]));
            }
            set {
                this["mainWindowMarginY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemsWindowMarginX {
            get {
                return ((string)(this["itemsWindowMarginX"]));
            }
            set {
                this["itemsWindowMarginX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemsWindowMarginY {
            get {
                return ((string)(this["itemsWindowMarginY"]));
            }
            set {
                this["itemsWindowMarginY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemsWidth {
            get {
                return ((string)(this["itemsWidth"]));
            }
            set {
                this["itemsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string itemsHeight {
            get {
                return ((string)(this["itemsHeight"]));
            }
            set {
                this["itemsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string buttonMarginX {
            get {
                return ((string)(this["buttonMarginX"]));
            }
            set {
                this["buttonMarginX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string buttonMarginY {
            get {
                return ((string)(this["buttonMarginY"]));
            }
            set {
                this["buttonMarginY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingItemsBorder {
            get {
                return ((bool)(this["settingItemsBorder"]));
            }
            set {
                this["settingItemsBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingChestGreen {
            get {
                return ((bool)(this["settingChestGreen"]));
            }
            set {
                this["settingChestGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingChestBlue {
            get {
                return ((bool)(this["settingChestBlue"]));
            }
            set {
                this["settingChestBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ettingChestPurple {
            get {
                return ((bool)(this["ettingChestPurple"]));
            }
            set {
                this["ettingChestPurple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingChestYellow {
            get {
                return ((bool)(this["settingChestYellow"]));
            }
            set {
                this["settingChestYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistSolo {
            get {
                return ((bool)(this["settingMistSolo"]));
            }
            set {
                this["settingMistSolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistDuo {
            get {
                return ((bool)(this["settingMistDuo"]));
            }
            set {
                this["settingMistDuo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistE0 {
            get {
                return ((bool)(this["settingMistE0"]));
            }
            set {
                this["settingMistE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistE1 {
            get {
                return ((bool)(this["settingMistE1"]));
            }
            set {
                this["settingMistE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistE2 {
            get {
                return ((bool)(this["settingMistE2"]));
            }
            set {
                this["settingMistE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistE3 {
            get {
                return ((bool)(this["settingMistE3"]));
            }
            set {
                this["settingMistE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMistE4 {
            get {
                return ((bool)(this["settingMistE4"]));
            }
            set {
                this["settingMistE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingCage {
            get {
                return ((bool)(this["settingCage"]));
            }
            set {
                this["settingCage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonSolo {
            get {
                return ((bool)(this["settingDungeonSolo"]));
            }
            set {
                this["settingDungeonSolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonDuo {
            get {
                return ((bool)(this["settingDungeonDuo"]));
            }
            set {
                this["settingDungeonDuo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonE0 {
            get {
                return ((bool)(this["settingDungeonE0"]));
            }
            set {
                this["settingDungeonE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonE1 {
            get {
                return ((bool)(this["settingDungeonE1"]));
            }
            set {
                this["settingDungeonE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonE2 {
            get {
                return ((bool)(this["settingDungeonE2"]));
            }
            set {
                this["settingDungeonE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonE3 {
            get {
                return ((bool)(this["settingDungeonE3"]));
            }
            set {
                this["settingDungeonE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonE4 {
            get {
                return ((bool)(this["settingDungeonE4"]));
            }
            set {
                this["settingDungeonE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonCorrupted {
            get {
                return ((bool)(this["settingDungeonCorrupted"]));
            }
            set {
                this["settingDungeonCorrupted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingDungeonHellgate {
            get {
                return ((bool)(this["settingDungeonHellgate"]));
            }
            set {
                this["settingDungeonHellgate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingFootTracksSolo {
            get {
                return ((bool)(this["settingFootTracksSolo"]));
            }
            set {
                this["settingFootTracksSolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingFootTracksGroup {
            get {
                return ((bool)(this["settingFootTracksGroup"]));
            }
            set {
                this["settingFootTracksGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingAllEnemies {
            get {
                return ((bool)(this["settingAllEnemies"]));
            }
            set {
                this["settingAllEnemies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingNormalEnemy {
            get {
                return ((bool)(this["settingNormalEnemy"]));
            }
            set {
                this["settingNormalEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMediumEnemy {
            get {
                return ((bool)(this["settingMediumEnemy"]));
            }
            set {
                this["settingMediumEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingEnchantedEnemy {
            get {
                return ((bool)(this["settingEnchantedEnemy"]));
            }
            set {
                this["settingEnchantedEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingMiniBossEnemy {
            get {
                return ((bool)(this["settingMiniBossEnemy"]));
            }
            set {
                this["settingMiniBossEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingBossEnemy {
            get {
                return ((bool)(this["settingBossEnemy"]));
            }
            set {
                this["settingBossEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingBossCrystalSpider {
            get {
                return ((bool)(this["settingBossCrystalSpider"]));
            }
            set {
                this["settingBossCrystalSpider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingBossFairyDragon {
            get {
                return ((bool)(this["settingBossFairyDragon"]));
            }
            set {
                this["settingBossFairyDragon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingBossVeilWeaver {
            get {
                return ((bool)(this["settingBossVeilWeaver"]));
            }
            set {
                this["settingBossVeilWeaver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingBossGriffin {
            get {
                return ((bool)(this["settingBossGriffin"]));
            }
            set {
                this["settingBossGriffin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingAvaloneDrones {
            get {
                return ((bool)(this["settingAvaloneDrones"]));
            }
            set {
                this["settingAvaloneDrones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingShowUnmanagedEnemies {
            get {
                return ((bool)(this["settingShowUnmanagedEnemies"]));
            }
            set {
                this["settingShowUnmanagedEnemies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingShowEventEnemies {
            get {
                return ((bool)(this["settingShowEventEnemies"]));
            }
            set {
                this["settingShowEventEnemies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string settingMinHP {
            get {
                return ((string)(this["settingMinHP"]));
            }
            set {
                this["settingMinHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingEnemiesHP {
            get {
                return ((bool)(this["settingEnemiesHP"]));
            }
            set {
                this["settingEnemiesHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingEnemiesID {
            get {
                return ((bool)(this["settingEnemiesID"]));
            }
            set {
                this["settingEnemiesID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFiberE0 {
            get {
                return ((string)(this["settingFiberE0"]));
            }
            set {
                this["settingFiberE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFiberE1 {
            get {
                return ((string)(this["settingFiberE1"]));
            }
            set {
                this["settingFiberE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFiberE2 {
            get {
                return ((string)(this["settingFiberE2"]));
            }
            set {
                this["settingFiberE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFiberE3 {
            get {
                return ((string)(this["settingFiberE3"]));
            }
            set {
                this["settingFiberE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFiberE4 {
            get {
                return ((string)(this["settingFiberE4"]));
            }
            set {
                this["settingFiberE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHideE0 {
            get {
                return ((string)(this["settingHideE0"]));
            }
            set {
                this["settingHideE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHideE1 {
            get {
                return ((string)(this["settingHideE1"]));
            }
            set {
                this["settingHideE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHideE2 {
            get {
                return ((string)(this["settingHideE2"]));
            }
            set {
                this["settingHideE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHideE3 {
            get {
                return ((string)(this["settingHideE3"]));
            }
            set {
                this["settingHideE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingHideE4 {
            get {
                return ((string)(this["settingHideE4"]));
            }
            set {
                this["settingHideE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingWoodE0 {
            get {
                return ((string)(this["settingWoodE0"]));
            }
            set {
                this["settingWoodE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingWoodE1 {
            get {
                return ((string)(this["settingWoodE1"]));
            }
            set {
                this["settingWoodE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingWoodE2 {
            get {
                return ((string)(this["settingWoodE2"]));
            }
            set {
                this["settingWoodE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingWoodE3 {
            get {
                return ((string)(this["settingWoodE3"]));
            }
            set {
                this["settingWoodE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingWoodE4 {
            get {
                return ((string)(this["settingWoodE4"]));
            }
            set {
                this["settingWoodE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingRockE0 {
            get {
                return ((string)(this["settingRockE0"]));
            }
            set {
                this["settingRockE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingRockE1 {
            get {
                return ((string)(this["settingRockE1"]));
            }
            set {
                this["settingRockE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingRockE2 {
            get {
                return ((string)(this["settingRockE2"]));
            }
            set {
                this["settingRockE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingRockE3 {
            get {
                return ((string)(this["settingRockE3"]));
            }
            set {
                this["settingRockE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingRockE4 {
            get {
                return ((string)(this["settingRockE4"]));
            }
            set {
                this["settingRockE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOreE0 {
            get {
                return ((string)(this["settingOreE0"]));
            }
            set {
                this["settingOreE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOreE1 {
            get {
                return ((string)(this["settingOreE1"]));
            }
            set {
                this["settingOreE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOreE2 {
            get {
                return ((string)(this["settingOreE2"]));
            }
            set {
                this["settingOreE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOreE3 {
            get {
                return ((string)(this["settingOreE3"]));
            }
            set {
                this["settingOreE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOreE4 {
            get {
                return ((string)(this["settingOreE4"]));
            }
            set {
                this["settingOreE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDryadFiberE0 {
            get {
                return ((string)(this["settingDryadFiberE0"]));
            }
            set {
                this["settingDryadFiberE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDryadFiberE1 {
            get {
                return ((string)(this["settingDryadFiberE1"]));
            }
            set {
                this["settingDryadFiberE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDryadFiberE2 {
            get {
                return ((string)(this["settingDryadFiberE2"]));
            }
            set {
                this["settingDryadFiberE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDryadFiberE3 {
            get {
                return ((string)(this["settingDryadFiberE3"]));
            }
            set {
                this["settingDryadFiberE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDryadFiberE4 {
            get {
                return ((string)(this["settingDryadFiberE4"]));
            }
            set {
                this["settingDryadFiberE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingAnimalsHideE0 {
            get {
                return ((string)(this["settingAnimalsHideE0"]));
            }
            set {
                this["settingAnimalsHideE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingAnimalsHideE1 {
            get {
                return ((string)(this["settingAnimalsHideE1"]));
            }
            set {
                this["settingAnimalsHideE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingAnimalsHideE2 {
            get {
                return ((string)(this["settingAnimalsHideE2"]));
            }
            set {
                this["settingAnimalsHideE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingAnimalsHideE3 {
            get {
                return ((string)(this["settingAnimalsHideE3"]));
            }
            set {
                this["settingAnimalsHideE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingAnimalsHideE4 {
            get {
                return ((string)(this["settingAnimalsHideE4"]));
            }
            set {
                this["settingAnimalsHideE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpiritWoodE0 {
            get {
                return ((string)(this["settingSpiritWoodE0"]));
            }
            set {
                this["settingSpiritWoodE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpiritWoodE1 {
            get {
                return ((string)(this["settingSpiritWoodE1"]));
            }
            set {
                this["settingSpiritWoodE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpiritWoodE2 {
            get {
                return ((string)(this["settingSpiritWoodE2"]));
            }
            set {
                this["settingSpiritWoodE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpiritWoodE3 {
            get {
                return ((string)(this["settingSpiritWoodE3"]));
            }
            set {
                this["settingSpiritWoodE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingSpiritWoodE4 {
            get {
                return ((string)(this["settingSpiritWoodE4"]));
            }
            set {
                this["settingSpiritWoodE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalOreE0 {
            get {
                return ((string)(this["settingElementalOreE0"]));
            }
            set {
                this["settingElementalOreE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalOreE1 {
            get {
                return ((string)(this["settingElementalOreE1"]));
            }
            set {
                this["settingElementalOreE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalOreE2 {
            get {
                return ((string)(this["settingElementalOreE2"]));
            }
            set {
                this["settingElementalOreE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalOreE3 {
            get {
                return ((string)(this["settingElementalOreE3"]));
            }
            set {
                this["settingElementalOreE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalOreE4 {
            get {
                return ((string)(this["settingElementalOreE4"]));
            }
            set {
                this["settingElementalOreE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalRockE0 {
            get {
                return ((string)(this["settingElementalRockE0"]));
            }
            set {
                this["settingElementalRockE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalRockE1 {
            get {
                return ((string)(this["settingElementalRockE1"]));
            }
            set {
                this["settingElementalRockE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalRockE2 {
            get {
                return ((string)(this["settingElementalRockE2"]));
            }
            set {
                this["settingElementalRockE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalRockE3 {
            get {
                return ((string)(this["settingElementalRockE3"]));
            }
            set {
                this["settingElementalRockE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingElementalRockE4 {
            get {
                return ((string)(this["settingElementalRockE4"]));
            }
            set {
                this["settingElementalRockE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOtherE0 {
            get {
                return ((string)(this["settingOtherE0"]));
            }
            set {
                this["settingOtherE0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOtherE1 {
            get {
                return ((string)(this["settingOtherE1"]));
            }
            set {
                this["settingOtherE1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOtherE2 {
            get {
                return ((string)(this["settingOtherE2"]));
            }
            set {
                this["settingOtherE2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOtherE3 {
            get {
                return ((string)(this["settingOtherE3"]));
            }
            set {
                this["settingOtherE3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingOtherE4 {
            get {
                return ((string)(this["settingOtherE4"]));
            }
            set {
                this["settingOtherE4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingFishingPool {
            get {
                return ((string)(this["settingFishingPool"]));
            }
            set {
                this["settingFishingPool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingDebug {
            get {
                return ((string)(this["settingDebug"]));
            }
            set {
                this["settingDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingShowSize {
            get {
                return ((string)(this["settingShowSize"]));
            }
            set {
                this["settingShowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingShowHP {
            get {
                return ((string)(this["settingShowHP"]));
            }
            set {
                this["settingShowHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string settingShowID {
            get {
                return ((string)(this["settingShowID"]));
            }
            set {
                this["settingShowID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreList {
            get {
                return ((string)(this["IgnoreList"]));
            }
            set {
                this["IgnoreList"] = value;
            }
        }
    }
}
